name: Build
run-name: Build the project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1-beta
        with:
          check-reservoir-eligibility: true
      # use setup from lean-action to perform the following steps
      - name: print lean and lake versions
        run: |
          lean --version
          lake --version
      - name: verify `lake exe graph` works
        run: |
          lake exe graph
          rm import_graph.dot
